#!/bin/sh
#
#########################################################################
# Script Name   : check_asterisk_reverse_search                         #
# Description   : Checks the specified numbers (for which there must    #
#                 be backward search results!) against the Asterisk     #
#                 reverse search script and sends an email with a       #
#                 warning message if the search result is not positive. #
#                                                                       #
#                 The only restriction is the double search for German  #
#                 telephone numbers; the secondary search via Klicktel  #
#                 cannot be effectively checked here.                   #
#                                                                       #
#                 Runs automatically by a Cron-Job                      #
#                 -based on a Script Superslub                          #
#                 -https://github.com/Superslub/AGI_Reverse_Lookup_DACH #
# Args          :                                                       #
#                                                                       #
# Version       : 1.00                                                  #
# Last Update   : 20.03.2021                                            #
# Author        : Twilight                                              #
# Email         : twilight@twlnet.com                                   #
# Web:          : https://www.twilight-networks.com                     #
#########################################################################
# Tested with   : Ubuntu 18.04 LTS                                      #
#                 Asterisk 18.2.0                                       #
#########################################################################


# Asterisk AGI-Dir
AGIDIR='/var/lib/asterisk/agi-bin'

# Reports are sent to
MAILTO='root@twlnet.com'

# Reports are sent by
MAILFROM='sip@twlnet.tld'

# Numbers to check
numbers='
 0049762113311
 00492315340048
'




# Normaly there is no need to change anything below this comment line!
#########################################################################

for num in $numbers; do
    out=`while true; do echo " \n"; sleep 0.1; done | perl ${AGIDIR}/reverse_search.agi $num  0 0 1 1 | grep 'Nummer nicht gefunden'`
    if [ -n "$out" ]
    then
    	(
        	echo "$num NOT OK - sende Mail"
        ) 2>&1 | logger 
	            (
	                echo "Content-Type: text/plain; charset="UTF-8""
	                echo "To: <${MAILTO}>"
	                echo "MIME-Version: 1.0"
	                echo "From: $(hostname -f)  <${MAILFROM}>"
	            
	                echo "Subject: Asterisk Reverse-Search prüfen"
	                echo
	                echo "$num konnte nicht gefunden werden."
	                echo
	                echo "Bitte Parser unter ${AGIDIR}/reverse_search.agi prüfen und evtl. anpassen!"
	                echo
	            ) 2>&1 | /usr/lib/sendmail -t
        exit 0
    else
    	(
        	echo "$num OK"
        ) 2>&1 | logger 
    fi
done
#end